# Generated by Django 6.0.3 on 2026-03-13 17:58

import vouch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouch', '0002_introchain_introstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_invites',
        ),
        migrations.AddField(
            model_name='invite',
            name='expires_at',
            field=models.DateTimeField(default=vouch.models.default_invite_expiry),
        ),
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
