# Generated by Django 6.0.3 on 2026-03-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouch', '0003_remove_user_available_invites_invite_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='introstep',
            name='is_final',
            field=models.BooleanField(default=False, help_text='True if this is the final step where the target accepts/rejects'),
        ),
    ]
