# Generated by Django 6.0.3 on 2026-03-13 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouch', '0006_tempchat_tempchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('professional', 'Professional'), ('student', 'Student')], default='professional', max_length=20),
        ),
        migrations.AlterField(
            model_name='introstep',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('intro_forward', 'Intro Forward Request'), ('intro_accepted', 'Intro Accepted'), ('intro_rejected', 'Intro Rejected'), ('connection_new', 'New Connection'), ('connection_removed', 'Connection Removed'), ('temp_chat_request', 'Temp Chat Request'), ('temp_chat_active', 'Temp Chat Activated'), ('message', 'New Message')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
